# Create Programming interim table
CREATE TABLE programming AS SELECT * FROM src_prgdef_bskdef;

# Drop uneeded cols
ALTER TABLE programming 
DROP `"BRANDOM"`,
DROP `"BPLAYMON"`,
DROP `"BPLAYTUE"`,
DROP `"BPLAYWED"`,
DROP `"BPLAYTHU"`,
DROP `"BPLAYFRI"`,
DROP `"BPLAYSAT"`,
DROP `"BPLAYSUN"`,
DROP `"RECURRENCE"`,
DROP `"TIMESTMP"`;

# rename 
ALTER TABLE programming
ADD COLUMN id INT NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (id),
CHANGE `"ID_DEFPRG"` ID_DEFPRG INT(20),
CHANGE `"ID_DEFBSK"` ID_DEFBSK INT(20),
CHANGE `"PROG_LINE"` PROG_LINE INT(10),
CHANGE `"START_DATE"` START_DATE VARCHAR(50),
CHANGE `"END_DATE"` END_DATE VARCHAR(50),
CHANGE `"START_TIME"` START_TIME INT(20),
CHANGE `"END_TIME"` END_TIME INT(20),
CHANGE `"ID_LN_PRGDEF_BSKDEF"` ID_LN_PRGDEF_BSKDEF int(20);

# Add remaining cols
ALTER TABLE programming
ADD COLUMN PROGRAM_ID INT AFTER ID_DEFPRG,
ADD COLUMN PROGRAM VARCHAR(125) AFTER PROGRAM_ID,
ADD COLUMN BASKET_ID INT AFTER ID_DEFBSK,
ADD COLUMN BASKET VARCHAR(125) AFTER BASKET_ID,
ADD COLUMN BASKET_SIZE_SEC INT(11) AFTER END_TIME,
ADD COLUMN PROG_ITEM_DURATION_SEC INT(11) AFTER BASKET_SIZE_SEC,
ADD COLUMN TIME_SPAN VARCHAR(125) AFTER PROG_ITEM_DURATION_SEC,
ADD COLUMN PROG_ITEM_BSKT_PERC FLOAT(6,5) AFTER TIME_SPAN,
ADD COLUMN COUNTRY VARCHAR(75) AFTER PROG_ITEM_BSKT_PERC,
ADD COLUMN IS_ACTIVE INT(2) AFTER COUNTRY;

# # covering indexes
CREATE INDEX prog_id_prog_index
ON programming (PROGRAM_ID, PROGRAM);
CREATE INDEX bsk_id_bsk_index
ON programming (BASKET_ID, BASKET);
# index on prog and bsk
CREATE INDEX id_defprg ON programming (ID_DEFPRG);
CREATE INDEX id_defprg_index ON programming (PROGRAM_ID);
CREATE INDEX id_defbsk ON programming (ID_DEFBSK);
CREATE INDEX id_bsket_index ON programming (BASKET_ID);
CREATE INDEX prog_cover_index ON programming (PROGRAM);
CREATE INDEX bsk_cover_index ON programming (BASKET);
